### ISSUE TITLE
Enable SSL Pinning in Ionic apps

### ISSUE THREAD

**Issue by sckumar** [apollographql/apollo-angular#1008]
I am using apollo-angular in ionic apps.
I wanted to do SSL pinning for two different platforms (iOS and android)
Is there any cordova plugins available for apollo client so that I can enhance the plugin to validate SSL pinning?

**Comment by sckumar** [comment]
@kamilkisiela It can't be done via apollo links or middleware ?

**Comment by kamilkisiela** [comment]
@sckumar could you share more? I'm not familiar with Ionic on iOS or Android. I think since Apollo Client relies on Angular's `HttpClient` then if it's possible to do it with `HttpClient` it's also possible in Apollo. If not then maybe a custom link?

I'm closing this one since it's not related to the library itself but if you could share with me more info then maybe we could reopen it?
