### ISSUE TITLE
Query sent multiple times on one request.

### ISSUE THREAD

**Issue by mluis** [apollographql/apollo-angular#1322]
**Intended outcome:**

`.valueChanges.subscribe(callback)` would call `callback` one time only.

**Actual outcome:**

`.valueChanges.subscribe(callback)` calls `callback` multiple times with no ending.

**How to reproduce the issue:**

```
.. .valueChanges.subscribe( r -> { this.apollo.watchQuery(...).valueChanges.subscribe(callback)} )
```
**Versions**

"typescript": "~3.4.3"
"@angular/core": "~8.1.2"
"apollo-angular": "^1.7.0",
"graphql": "^14.5.4",

**Comment by kamilkisiela** [comment]
Could you create a small reproduction so I could understand what exactly happens?

`this.apollo.watchQuery().valueChanges` may emit multiple results because you watch for a query (both network and then store) and not fetching it once. When you already have its result in the cache and you use `network-and-cache` policy or something similar then it first, emits the cached result and then reaches the network and gives you back another result, the fresh one from graphql api.

In order to get the result only once, you should either use `this.apollo.query()` or use `first()` or `take()` rxjs operators (or similar).

**Comment by mluis** [comment]
Thanks @kamilkisiela , after I switched to this.apollo.query() the issue no longer happens.
