### ISSUE TITLE
Confusion with angular2-apollo package in npm

### ISSUE THREAD

**Issue by kemalcany** [apollographql/apollo-angular#273]
Hi guys,

The github link on https://www.npmjs.com/package/angular2-apollo directs to this repo, but there are two different repos in npm. Is the angular2-apollo still alive? Any ideas?

Cheers

**Comment by kamilkisiela** [comment]
Hi :)

Since [`v0.9.0`](https://github.com/apollographql/apollo-angular/blob/master/CHANGELOG.md#v090) we've changed the name of this package to `apollo-angular`, so `angular2-apollo` is now deprecated.

I think we're going to write a blog post about recent changes to make it more clear to everyone :)
