### ISSUE TITLE
Observables from 2 different requests are connected

### ISSUE THREAD

**Issue by Vi-dot** [apollographql/apollo-angular#324]
Hello,

I have two different requests, they have nothing to do together.
But their Observables are connected for no reason.

A first one is called (after a route applied) :
```javascript
this.apollo.watchQuery({
      query: this.getReq
    }).subscribe(({data}) => {
      console.log('getReq success');
    },(error) => {});
```
Console
```batch
> getReq success
```
-----------------------------------------------
Then a second one is called (when clicking on a button) :
```javascript
this.apollo.mutate({
      mutation: this.updateReq,
      variables: {
        id: _id,
        key: _key,
        value: _value
      }
    }).subscribe(({data}) => {
      console.log('updateReq success');
    },(error) => {});
```
Console
```batch
> updateReq success
> getReq success
```

Why `getReq` is called there ?
Thanks

**Comment by kamilkisiela** [comment]
@Vi-dot Does the result of the first one stays the same?
I think that store updates itself because of the mutation and then in result the watched query fires again. 

In ApolloClient you have an option that specifies the way of getting an ID from an object, it's called `dataIdFromObject`. By default it checks if the result contains a `__typename` and one of these: `id` or `_id`. Thanks to that the store knows which data needs to be updated.

First of all, check if you add a `__typename` to the query, if not maybe your ApolloClient instance has `addTypename` set to true. If it does and your query contains a field with ID (`id` or `_id`) then this is probably it.

**Comment by eitanfr** [comment]
from the doc:

> When we use mutations in Apollo, the result is typically integrated into the cache automatically based on the id of the result, which in turn updates UI automatically, so we don’t explicitly handle the results ourselves. In order for the client to correctly do this, we need to ensure we select the correct fields (as in all the fields that we care about that may have changed).

I am guessing that you mutate the same data you are querying  that why you see updateReq and then getReq

**Comment by Vi-dot** [comment]
Thanks you both, you're right I mutate an element which is a part of `getReq`results, with the same `__typename` and `id`.
I understand how this feature can be useful, but in my case, I prefer to call getReq only when I decided. An option may do that ?

**Comment by Vi-dot** [comment]
I found it ! What I need was _prefetching data_
replace `watchQuery` by `query`
Thanks for your work
Solved
