### ISSUE TITLE
Server side rendering error with angular 4

### ISSUE THREAD

**Issue by ngocdiep** [apollographql/apollo-angular#344]
Hi,
  I get the project from https://github.com/angular/universal-starter and add the apollo-angular. It works perfectly in the client side rendering but not in the server side rendering (it shows error log: 'Error: Network error: fetch is not defined')

 Could someone help me how to fix it?

Best thanks!!!

**Comment by kamilkisiela** [comment]
Try to add `isomorphic-fetch` to dependencies and import it at the very beginning of your source code.

Quite some time ago I created a working example of that starter with usage of Apollo.
https://github.com/kamilkisiela/universal-starter-apollo

Because Angular Team change the way they handle async operations in SSR I'll try to implement those changes in apollo-angular soon

**Comment by ngocdiep** [comment]
Hi @kamilkisiela,
  Thanks for your support, it works now 😊
Thank you!
