### ISSUE TITLE
Is apollo-angular still being maintained?

### ISSUE THREAD

**Issue by viztastic** [apollographql/apollo-angular#346]
@kamilkisiela I can't help but notice that the releases have slowed down significantly since earlier this year. Is apollo-angular still being actively maintained? 

Thanks!

**Comment by kamilkisiela** [comment]
I'm still keeping an eye on it. Currently, there is an issue with `apollo-client-rxjs` package that I'm trying to resolve. Also, SSR is not working which I fixed already but still waiting to release everything at once.

It's true that pushing updates slowed down. That's because I have other project and besides those two issues there's nothing significant to do with `apollo-angular`. I mean, I don't need anything new in my projects. 

Soooo if you all want to push something forward, you can message me directly, or using github issues, I would help you with a PR etc.

**Comment by Uter1007** [comment]
keep up that great work.

**Comment by picosam** [comment]
Hello @kamilkisiela! I've noticed you released an RC of `apollo-client-rxjs` 11 days ago. Is this what needs to be updated in this project so that compilation with Typescript 2.4 would work?

**Comment by kamilkisiela** [comment]
Hi all!

Great news! Brand new version `apollo-angular` is coming soon! Expect the first alpha version in next two / three days

**Comment by kamilkisiela** [comment]
Preview of future 1.0 #377 
I had no sleep in recent few days :)

**Comment by kamilkisiela** [comment]
I'm closing this one :) Thanks guys for supporting me ;)
