### ISSUE TITLE
Upgrade to GraphQL 14

### ISSUE THREAD

**Issue by NaLLiFFuNT** [apollographql/apollo-angular#850]
I have just get updated to graphql 14. I have updated all Apollo packages & Apollo-angular to latest versions, removed `package-lock.json` & `node modules`, run `npm i`
But i steel see this notice in console.
```
npm WARN apollo-angular-link-http@1.2.0 requires a peer of graphql@^0.11.3 || ^0.12.3 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-angular-link-http-common@1.2.0 requires a peer of graphql@^0.11.3 || ^0.12.3 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

```

my package.json deps:
```
    "@types/graphql": "^14.0.1",
    "apollo-angular": "^1.3.0",
    "apollo-angular-link-http": "^1.2.0",
    "apollo-cache-inmemory": "^1.2.10",
    "apollo-client": "^2.4.2",
    "apollo-link-error": "^1.1.1",
    "graphql": "14.0.2",
    "graphql-tag": "^2.9.2",
    "apollo-link-schema": "^1.1.1",
    "graphql-tools": "^4.0.0",
```

**Comment by kamilkisiela** [comment]
@NaLLiFFuNT It's just a warning, it doesn't change anything in your app. If you want to help please PR a change.

**Comment by selipso** [comment]
This version upgrade fixes a current incompatibility with apollo-link-state in the new Ionic Beta with Angular 6 in Desktop Safari. Otherwise, graphql throws an error along the lines of 'process not found or undefined'. 

I think this change would need to be made to the schematic responsible for adding graphql through `ng add apollo-angular`.

**Comment by NaLLiFFuNT** [comment]
There's something else should be done too. #857
