### ISSUE TITLE
After mutation, calling watchQuery method is not fetching the latest data

### ISSUE THREAD

**Issue by protagonist51** [apollographql/apollo-angular#980]
After I do a mutation, I'm calling  watchQuery method to fetch the updated rows but its still fetching the old data.

```
public saveSite() {
    const _site = JSON.parse(JSON.stringify(this.siteForm.value));
    this.apollo.mutate({
      mutation: createSite,
      variables: {
        site_name: _site.name,
        desc: _site.desc,
        site_type_id: _site.sitetype
      }
    }).subscribe((dataVal) => {
      this.loading = dataVal.loading;
      this.errors = dataVal.errors;
      this.getSiteList();
    }, (error) => {
      this.errors = error;
    });
  }

public getSiteList() {
    this.loading = true;
    this.querySubscription = this.apollo
      .watchQuery({
        query: gql`
          {
            cmp_site{
              id
              desc
              site_name
              site_type_id
              sitetype{
                id
                name
              }
            }
          }
        `
      })
      .valueChanges.subscribe(result => {
        const sitedata: any = result.data;
        this.sites = sitedata.cmp_site;
        this.loading = result.loading;
        this.error = result.errors;
      });
```

Its not fetching the latest data.

**Comment by kamilkisiela** [comment]
Your example doesn't say much because there's no GraphQL Operations but I will assume that you're not doing anything special with the ApolloCache's configuration. That would mean that the cache won't be updated and your query will still get an old data because you didn't tell Apollo to invalidate it. Apollo can't guess that you'r mutation's result matches a query, you have to explicitly tell that to Apollo.

You can either use proper `fetchPolicy` in watchQuery's options or update the cache that's to mutation's api.

https://www.apollographql.com/docs/angular/features/cache-updates.html

Please @mention me here if this didn't help you so I could reopen the issue.
