### ISSUE TITLE
Add support to get active requests in Apollo Client

### ISSUE THREAD

**Issue by petrovic-ivan** [apollographql/apollo-angular#988]
1. **Use case**: I would like to have option to see does Apollo Client processing some network request or doesn't processing anything. By processing requests I meant to see currently running operations such as query or mutation. These information I can use to make generic way for e.g. displaying progress bars which indicate that network requests are in progress in application.

2. **Could this be a plugin?** Maybe it can be extension to existing client or can be another **link**.

3. **Is there a workaround?** Developer can create **link** which logs when request started and ended. Based on those information we can see does Apollo Client processing any query/mutation or not processing.

**Comment by kamilkisiela** [comment]
Actually it might be very handy :) good idea. I think having it based on an Apollo Link is enough. I would implement it this way:

- Apollo Link created on Dependency Injection level that is also an angular service or is connected to a separate service.
- Because of the service, your angular app will know what's going on with the requests.
- Inside one of your components you could inject that service and show/hide loading spinner based on it
- The Apollo Link should be used before a terminating link, usually before HttpLink.

I guess I can help you implementing that, PR welcome. I'm @kamil on [Apollo's slack](https://www.apollographql.com/slack), we also have #apollo-angular channel :) If you're willing to start working on the link and need my help, let me know!

**Comment by kamilkisiela** [comment]
I forgot I wrote something few weeks ago `apollo-angular-link-network-status`

Repo: https://github.com/kamilkisiela/apollo-angular-link-network-status
Example: https://stackblitz.com/edit/apollo-angular-network-status?file=app%2Fgraphql.module.ts

**Comment by kamilkisiela** [comment]
Closing, please @mention me if it's still relevant
